/**
 * mockData.js
 * Isolated mock data layer – swap out for real API responses
 * when backend integration is ready.
 */

export const MOCK_ANALYSIS_RESULT = {
  sessionId: "session_a7f3c2d1",
  analyzedAt: new Date().toISOString(),
  totalFiles: 5,
  totalPairs: 10,
  pairs: [
    {
      id: "pair_001",
      file1: "solution_alice.cpp",
      file2: "solution_bob.cpp",
      jaccardSimilarity: 0.91,
      cosineSimilarity: 0.94,
      containmentA: 0.96,
      containmentB: 0.89,
      commonHashes: 182,
      totalHashesA: 190,
      totalHashesB: 204,
      riskLevel: "HIGH",
    },
    {
      id: "pair_002",
      file1: "matrix.py",
      file2: "linear_algebra.py",
      jaccardSimilarity: 0.67,
      cosineSimilarity: 0.71,
      containmentA: 0.73,
      containmentB: 0.64,
      commonHashes: 134,
      totalHashesA: 183,
      totalHashesB: 209,
      riskLevel: "MEDIUM",
    },
    {
      id: "pair_003",
      file1: "sort_impl.c",
      file2: "utils.c",
      jaccardSimilarity: 0.38,
      cosineSimilarity: 0.42,
      containmentA: 0.44,
      containmentB: 0.36,
      commonHashes: 76,
      totalHashesA: 200,
      totalHashesB: 211,
      riskLevel: "LOW",
    },
    {
      id: "pair_004",
      file1: "graph.java",
      file2: "tree.java",
      jaccardSimilarity: 0.14,
      cosineSimilarity: 0.18,
      containmentA: 0.16,
      containmentB: 0.12,
      commonHashes: 28,
      totalHashesA: 200,
      totalHashesB: 233,
      riskLevel: "SAFE",
    },
    {
      id: "pair_005",
      file1: "solution_alice.cpp",
      file2: "sort_impl.c",
      jaccardSimilarity: 0.21,
      cosineSimilarity: 0.25,
      containmentA: 0.23,
      containmentB: 0.19,
      commonHashes: 42,
      totalHashesA: 200,
      totalHashesB: 221,
      riskLevel: "SAFE",
    },
    {
      id: "pair_006",
      file1: "matrix.py",
      file2: "graph.java",
      jaccardSimilarity: 0.09,
      cosineSimilarity: 0.11,
      containmentA: 0.10,
      containmentB: 0.08,
      commonHashes: 18,
      totalHashesA: 183,
      totalHashesB: 225,
      riskLevel: "SAFE",
    },
    {
      id: "pair_007",
      file1: "solution_bob.cpp",
      file2: "utils.c",
      jaccardSimilarity: 0.55,
      cosineSimilarity: 0.61,
      containmentA: 0.63,
      containmentB: 0.54,
      commonHashes: 110,
      totalHashesA: 204,
      totalHashesB: 203,
      riskLevel: "MEDIUM",
    },
    {
      id: "pair_008",
      file1: "linear_algebra.py",
      file2: "sort_impl.c",
      jaccardSimilarity: 0.12,
      cosineSimilarity: 0.15,
      containmentA: 0.14,
      containmentB: 0.11,
      commonHashes: 25,
      totalHashesA: 209,
      totalHashesB: 200,
      riskLevel: "SAFE",
    },
    {
      id: "pair_009",
      file1: "graph.java",
      file2: "utils.c",
      jaccardSimilarity: 0.06,
      cosineSimilarity: 0.08,
      containmentA: 0.07,
      containmentB: 0.05,
      commonHashes: 12,
      totalHashesA: 200,
      totalHashesB: 211,
      riskLevel: "SAFE",
    },
    {
      id: "pair_010",
      file1: "tree.java",
      file2: "linear_algebra.py",
      jaccardSimilarity: 0.78,
      cosineSimilarity: 0.82,
      containmentA: 0.84,
      containmentB: 0.75,
      commonHashes: 156,
      totalHashesA: 186,
      totalHashesB: 207,
      riskLevel: "HIGH",
    },
  ],
};

/**
 * Simulated code diff segments for side-by-side comparison (future feature).
 * Keys are pair IDs.
 */
export const MOCK_CODE_DIFF = {
  pair_001: {
    file1Lines: [
      { line: 1, content: "#include <bits/stdc++.h>", flagged: false },
      { line: 2, content: "using namespace std;", flagged: false },
      { line: 3, content: "", flagged: false },
      { line: 4, content: "int main() {", flagged: true },
      { line: 5, content: "  int n; cin >> n;", flagged: true },
      { line: 6, content: "  vector<int> a(n);", flagged: true },
      { line: 7, content: "  for (int i=0;i<n;i++) cin>>a[i];", flagged: true },
      { line: 8, content: "  sort(a.begin(),a.end());", flagged: true },
      { line: 9, content: "  cout << a[0] << endl;", flagged: true },
      { line: 10, content: "}", flagged: true },
    ],
    file2Lines: [
      { line: 1, content: "#include <bits/stdc++.h>", flagged: false },
      { line: 2, content: "using namespace std;", flagged: false },
      { line: 3, content: "", flagged: false },
      { line: 4, content: "int main(){", flagged: true },
      { line: 5, content: "  int n;cin>>n;", flagged: true },
      { line: 6, content: "  vector<int>a(n);", flagged: true },
      { line: 7, content: "  for(int i=0;i<n;i++)cin>>a[i];", flagged: true },
      { line: 8, content: "  sort(a.begin(),a.end());", flagged: true },
      { line: 9, content: "  cout<<a[0]<<\"\\n\";", flagged: true },
      { line: 10, content: "}", flagged: true },
    ],
  },
};
